CC = gcc
INC = -I ./inc
SRC = test.c \
      excercise/postorder_iterative.c \
      util/tree_util.c \
      excercise/size.c \
      excercise/height.c 

default:
	$(CC) $(INC) $(SRC)

clean:
	rm -rf *.o *.out
